// <auto-generated />
namespace Queue.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class acomodandocarggo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(acomodandocarggo));
        
        string IMigrationMetadata.Id
        {
            get { return "202105272245295_acomodando carggo "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
