// <auto-generated />
namespace Queue.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class finconfigurationtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(finconfigurationtable));
        
        string IMigrationMetadata.Id
        {
            get { return "202101252020542_fin configuration table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
