// <auto-generated />
namespace Queue.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addidcompanytoconfigurartion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addidcompanytoconfigurartion));
        
        string IMigrationMetadata.Id
        {
            get { return "202101251851485_add idcompany to configurartion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
